object Constants {
    val CPU_FREQUENCY_HZ = 500
    val CPU_PERIOD_MS = 2L
    val CPU_INSTRUCTION_BYTES = 2
    val CPU_PC_INCREMENT_DEFAULT = 2
    val CPU_INSTRUCTIONS_TOTAL = 16
    val RAM_SIZE_KB = 4
    val RAM_SIZE_BYTES = 4096
    val ROM_SIZE_KB = 4
    val ROM_SIZE_BYTES = 4096
    val PROGRAM_COUNTER_START_ADDRESS: UShort = 0x0000u
    val TIMER_DECREMENT_HZ = 60
    val TIMER_DECREMENT_MS = 16L
    val ASCII_DISPLAY_WIDTH_CHARS = 8
    val ASCII_DISPLAY_HEIGHT_CHARS = 8
    val ASCII_DISPLAY_BUFFER_SIZE_BYTES = 64
    val KEYBOARD_BUFFER_SIZE_BYTES = 1
}