object Constants {
    val CPU_FREQUENCY_HZ = 500
    val TIMER_DECREMENT_HZ = 60
    val RAM_SIZE_BYTES = 4096
    val ROM_SIZE_BYTES = 4096
    val ASCII_DISPLAY_WIDTH_CHARS = 8
    val ASCII_DISPLAY_HEIGHT_CHARS = 8
    val ASCII_DISPLAY_BUFFER_SIZE_CHARS = 64
    val KEYBOARD_BUFFER_SIZE_BYTES = 1
}